/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO:datasets:PyTorch version 2.3.1 available.
[nltk_data] Downloading package punkt to /home/borito1907/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt to /home/borito1907/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/borito1907/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
Error executing job with overrides: []
Traceback (most recent call last):
  File "/data2/borito1907/impossibility-watermark/attack/attack_eval.py", line 58, in main
    data = pd.read_csv('/data2/borito1907/impossibility-watermark/10_03_less_high_semstamp_good_embedder.csv')
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data2/borito1907/impossibility-watermark/10_03_less_high_semstamp_good_embedder.csv'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
