/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Traceback (most recent call last):
  File "messagestream.pyx", line 91, in scipy._lib.messagestream.MessageStream.close
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType
Exception ignored in: 'scipy._lib.messagestream.MessageStream.__dealloc__'
Traceback (most recent call last):
  File "messagestream.pyx", line 91, in scipy._lib.messagestream.MessageStream.close
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType
Traceback (most recent call last):
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 1535, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/pipelines/__init__.py", line 63, in <module>
    from .document_question_answering import DocumentQuestionAnsweringPipeline
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/pipelines/document_question_answering.py", line 29, in <module>
    from .question_answering import select_starts_ends
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/pipelines/question_answering.py", line 9, in <module>
    from ..data import SquadExample, SquadFeatures, squad_convert_examples_to_features
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/data/__init__.py", line 26, in <module>
    from .metrics import glue_compute_metrics, xnli_compute_metrics
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/data/metrics/__init__.py", line 19, in <module>
    from scipy.stats import pearsonr, spearmanr
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/scipy/stats/__init__.py", line 624, in <module>
    from ._rvs_sampling import rvs_ratio_uniforms
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/scipy/stats/_rvs_sampling.py", line 2, in <module>
    from scipy.stats.sampling import RatioUniforms
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/scipy/stats/sampling.py", line 59, in <module>
    from ._sampling import FastGeneratorInversion, RatioUniforms  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/scipy/stats/_sampling.py", line 8, in <module>
    from ._unuran.unuran_wrapper import NumericalInversePolynomial
  File "unuran_wrapper.pyx", line 188, in init scipy.stats._unuran.unuran_wrapper
  File "unuran_wrapper.pyx", line 167, in scipy.stats._unuran.unuran_wrapper._setup_unuran
  File "messagestream.pyx", line 29, in scipy._lib.messagestream.MessageStream.__cinit__
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/tempfile.py", line 357, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: b'/tmp/scipy-_znur6o3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local1/borito1907/impossibility-watermark/distinguisher.py", line 7, in <module>
    from utils import query_openai_with_history, get_prompt_or_output, get_watermarked_text, get_nth_successful_perturbation
  File "/local1/borito1907/impossibility-watermark/utils.py", line 159, in <module>
    from umd import UMDWatermarker
  File "/local1/borito1907/impossibility-watermark/umd.py", line 2, in <module>
    from watermarker import Watermarker
  File "/local1/borito1907/impossibility-watermark/watermarker.py", line 5, in <module>
    from model_builders.pipeline import PipeLineBuilder
  File "/local1/borito1907/impossibility-watermark/model_builders/__init__.py", line 1, in <module>
    from .pipeline import PipeLineBuilder
  File "/local1/borito1907/impossibility-watermark/model_builders/pipeline.py", line 3, in <module>
    from transformers import BitsAndBytesConfig, AutoModelForCausalLM, AutoTokenizer, pipeline, T5ForConditionalGeneration, AutoModel
  File "<frozen importlib._bootstrap>", line 1412, in _handle_fromlist
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 1525, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 1537, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
[Errno 28] No space left on device: b'/tmp/scipy-_znur6o3'
