2024-05-17 13:33:58,523:INFO:Running command: python distinguisher.py +distinguisher=llama3 ++distinguisher.log_suffix=05_17 ++distinguisher.entropy='"6"' ++distinguisher.output_1='"1"' ++distinguisher.attack_id_1='"3"' ++distinguisher.output_2='"2"' ++distinguisher.attack_id_2='"4"' 
2024-05-17 13:33:58,523:INFO:Saving results to ./results/stationary_distribution/robustness_analysis/entropy_6/distinguisher_results/1_3-2_4_05_17.log
Traceback (most recent call last):
  File "/local1/borito1907/impossibility-watermark/run_distinguisher.py", line 110, in <module>
    main()
  File "/local1/borito1907/impossibility-watermark/run_distinguisher.py", line 100, in main
    stdout, stderr = run_command(command, log_filepath)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/impossibility-watermark/run_distinguisher.py", line 79, in run_command
    result = subprocess.run(command, shell=True, check=True, text=True, stdout=f, stderr=subprocess.STDOUT)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/subprocess.py", line 2051, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/local1/borito1907/anaconda3/envs/watermark/lib/python3.12/subprocess.py", line 2009, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
