/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Traceback (most recent call last):
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data2/borito1907/impossibility-watermark/mutators/word.py", line 329, in <module>
    test()
  File "/data2/borito1907/impossibility-watermark/mutators/word.py", line 316, in test
    mutated_text = text_mutator.mutate(mutated_text)
  File "/data2/borito1907/impossibility-watermark/mutators/word.py", line 186, in mutate
    candidates = self.fill_mask(masked_text, top_k=3, tokenizer_kwargs=self.tokenizer_kwargs)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/pipelines/fill_mask.py", line 270, in __call__
    outputs = super().__call__(inputs, **kwargs)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1254, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1260, in run_single
    model_inputs = self.preprocess(inputs, **preprocess_params)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/pipelines/fill_mask.py", line 123, in preprocess
    self.ensure_exactly_one_mask_token(model_inputs)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/pipelines/fill_mask.py", line 112, in ensure_exactly_one_mask_token
    self._ensure_exactly_one_mask_token(input_ids)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/pipelines/fill_mask.py", line 100, in _ensure_exactly_one_mask_token
    raise PipelineException(
transformers.pipelines.base.PipelineException: No mask_token (<mask>) found on the input
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
Data saved to /data2/borito1907/impossibility-watermark/inputs/word_mutator/test_1new.csv
